spring:
  datasource:
    url: jdbc:postgresql://db.fmcmfgdbwzadjvvhmmyk.supabase.co:5432/postgres
    username: postgres
    password: 0WdV2VJp2wjiagJ2
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace




