spring:
  datasource:
    url: jdbc:postgresql://db-cosmic.c5268ca4wfrh.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: hyeonseok
    password: 12Qwaszx!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168


