on:
  push:
    branches:
      - main  # 배포할 브랜치 지정

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions에서 실행할 운영 체제를 지정

    steps:
    - name: Checkout Repository  # 저장소를 체크아웃하는 단계
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secrets에 저장된 SSH 개인 키 사용

    - name: Update apt packages  # apt 패키지 업데이트하는 단계
      run: sudo apt-get update

    - name: Install JVM  # JVM 설치하는 단계
      run: Sudo apt install openjdk-17-jdk -y

    - name: Upload JAR file to EC2  # 파일질라를 사용하여 JAR 파일을 EC2에 업로드하는 단계
      run: scp -i /User/hyeonseok/Desktop/AWS/mike.pem /User/hyeonseok/Desktop/SpartaProject/TodoList/build/libs/TodoList-0.0.1-SNAPSHOT.jar ubuntu@ec2-43-200-126-189.ap-northeast-2.compute.amazonaws.com

    - name: SSH into EC2 and start service  # EC2에 SSH로 연결하여 서비스 시작하는 단계
      run: ssh -i /User/hyeonseok/Desktop/AWS/mike.pem ubuntu@ec2-43-200-126-189.ap-northeast-2.compute.amazonaws.com 'java -jar /path/to/your/jar/file.jar'
