on:
  push:
    branches:
      - main  # 배포할 브랜치 지정

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions에서 실행할 운영 체제를 지정

    steps:
      - name: Checkout Repository  # 저장소를 체크아웃하는 단계
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secrets에 저장된 SSH 개인 키 사용

      - name: Update apt packages  # apt 패키지 업데이트하는 단계
        run: sudo apt-get update

      - name: Install JVM  # JVM 설치하는 단계
        run: Sudo apt install openjdk-17-jdk -y
